"""Generate shared visual tokens. Run with --check in CI to detect drift."""
import json
from pathlib import Path
import sys
root = Path(__file__).resolve().parents[1]
tokens = json.loads((root / 'packages/shared/design-tokens.json').read_text())
css = ['/* Generated by scripts/design_tokens.py. */']
dart = ["// Generated by scripts/design_tokens.py.", "import 'package:flutter/material.dart';", '', 'abstract final class VaeTokens {']
for mode in ['dark', 'light']:
    css.append(':root {' if mode == 'dark' else 'html[data-theme="light"] {')
    for name, value in tokens[mode].items():
        css.append(f'  --vae-{name}: {value};')
        dart.append(f'  static const {mode}{name.title()} = Color(0xFF{value[1:].upper()});')
    css.append('}')
for name,value in tokens['motionMs'].items():
    dart.append(f'  static const {name}Motion = Duration(milliseconds: {value});')
dart.append('}')
outputs = {'apps/web/app/design-tokens.css': '\n'.join(css)+'\n', 'apps/mobile/lib/theme/design_tokens.dart': '\n'.join(dart)+'\n'}
for path, content in outputs.items():
    target = root / path
    if '--check' in sys.argv:
        if not target.exists() or target.read_text(encoding='utf8') != content:
            raise SystemExit(f'Stale generated tokens: {path}')
    else:
        target.write_text(content, encoding='utf8')
