// Generated by scripts/design_tokens.py.
import 'package:flutter/material.dart';

abstract final class VaeTokens {
  static const darkBackground = Color(0xFF121016);
  static const darkInput = Color(0xFF211E24);
  static const darkSurface = Color(0xFF242127);
  static const darkRaised = Color(0xFF302B33);
  static const darkAccent = Color(0xFFE5485D);
  static const darkText = Color(0xFFF7F4F8);
  static const darkSuccess = Color(0xFF4E9C82);
  static const darkError = Color(0xFFEF6678);
  static const darkInfo = Color(0xFF8FA7C2);
  static const lightBackground = Color(0xFFF3F2F6);
  static const lightInput = Color(0xFFF6F4F8);
  static const lightSurface = Color(0xFFFFFFFF);
  static const lightRaised = Color(0xFFEEEAF2);
  static const lightAccent = Color(0xFFC72F47);
  static const lightText = Color(0xFF28212D);
  static const lightSuccess = Color(0xFF2F7A61);
  static const lightError = Color(0xFFB8273D);
  static const lightInfo = Color(0xFF3F6183);
  static const adminDarkBackground = Color(0xFF0D1420);
  static const adminDarkInput = Color(0xFF192230);
  static const adminDarkSurface = Color(0xFF1D2635);
  static const adminDarkRaised = Color(0xFF28364C);
  static const adminDarkAccent = Color(0xFF4F8CFF);
  static const adminDarkText = Color(0xFFF4F8FF);
  static const adminDarkSuccess = Color(0xFF58C7AA);
  static const adminDarkError = Color(0xFFEF6678);
  static const adminDarkInfo = Color(0xFF8BB6FF);
  static const adminLightBackground = Color(0xFFF0F3F9);
  static const adminLightInput = Color(0xFFF4F6FA);
  static const adminLightSurface = Color(0xFFFFFFFF);
  static const adminLightRaised = Color(0xFFE9EFF8);
  static const adminLightAccent = Color(0xFF2865D6);
  static const adminLightText = Color(0xFF14233D);
  static const adminLightSuccess = Color(0xFF2F8E75);
  static const adminLightError = Color(0xFFBD4054);
  static const adminLightInfo = Color(0xFF426FAF);
  static const controlMotion = Duration(milliseconds: 180);
  static const panelMotion = Duration(milliseconds: 360);
  static const pageMotion = Duration(milliseconds: 420);
}
