// Generated by scripts/design_tokens.py.
import 'package:flutter/material.dart';

abstract final class VaeTokens {
  static const darkBackground = Color(0xFF171014);
  static const darkInput = Color(0xFF21161B);
  static const darkSurface = Color(0xFF2A1C22);
  static const darkRaised = Color(0xFF35232A);
  static const darkAccent = Color(0xFFE5485D);
  static const darkText = Color(0xFFF7F2F4);
  static const darkSuccess = Color(0xFF4E9C82);
  static const darkError = Color(0xFFEF6678);
  static const darkInfo = Color(0xFF8FA7C2);
  static const lightBackground = Color(0xFFF8F3F4);
  static const lightInput = Color(0xFFFDF9FA);
  static const lightSurface = Color(0xFFFFFFFF);
  static const lightRaised = Color(0xFFF1E7E9);
  static const lightAccent = Color(0xFFC72F47);
  static const lightText = Color(0xFF211418);
  static const lightSuccess = Color(0xFF2F7A61);
  static const lightError = Color(0xFFB8273D);
  static const lightInfo = Color(0xFF3F6183);
  static const controlMotion = Duration(milliseconds: 160);
  static const panelMotion = Duration(milliseconds: 260);
  static const pageMotion = Duration(milliseconds: 520);
}
